// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smbiwdfbunwcxxhdzhft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYml3ZGZidW53Y3h4aGR6aGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTg5NjgsImV4cCI6MjA3MzE5NDk2OH0.4MIbGXW9cYv_UrtLrWCEo24rzOi7zUAvwtWk6lGqMqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});